create table if not exists public."user" (
  id bigint generated by default as identity primary key,
  username text not null unique,
  global_name text not null,
  email text not null unique,
  avatar text,
  created_at timestamptz not null default now()
);

create table if not exists public.channel (
  id bigint primary key,
  created_at timestamptz not null default now(),
  recepients bigint[] not null
);

create table if not exists public.friend (
  id bigint generated by default as identity primary key,
  id1 bigint not null references public."user"(id) on delete cascade,
  id2 bigint not null references public."user"(id) on delete cascade,
  are_friends boolean not null default false,
  "channelId" bigint references public.channel(id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint friend_not_self check (id1 <> id2)
);

create table if not exists public.message (
  id bigint primary key,
  channel_id bigint not null references public.channel(id) on delete cascade,
  author jsonb not null,
  content text not null,
  created_at timestamptz not null default now()
);

create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public."user" (username, global_name, email)
  values (
    coalesce(new.raw_user_meta_data->>'username', split_part(new.email, '@', 1)),
    coalesce(new.raw_user_meta_data->>'global_name', new.raw_user_meta_data->>'username', split_part(new.email, '@', 1)),
    new.email
  )
  on conflict (email) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_auth_user();

alter table public."user" enable row level security;
alter table public.channel enable row level security;
alter table public.friend enable row level security;
alter table public.message enable row level security;

drop policy if exists "read users" on public."user";
drop policy if exists "insert own profile" on public."user";
drop policy if exists "read channels" on public.channel;
drop policy if exists "insert channels" on public.channel;
drop policy if exists "read friends" on public.friend;
drop policy if exists "insert friends" on public.friend;
drop policy if exists "update friends" on public.friend;
drop policy if exists "read messages" on public.message;
drop policy if exists "insert messages" on public.message;

create policy "read users" on public."user"
for select using (true);

create policy "insert own profile" on public."user"
for insert with check (auth.role() = 'authenticated');

create policy "read channels" on public.channel
for select using (auth.role() = 'authenticated');

create policy "insert channels" on public.channel
for insert with check (auth.role() = 'authenticated');

create policy "read friends" on public.friend
for select using (auth.role() = 'authenticated');

create policy "insert friends" on public.friend
for insert with check (auth.role() = 'authenticated');

create policy "update friends" on public.friend
for update using (auth.role() = 'authenticated');

create policy "read messages" on public.message
for select using (auth.role() = 'authenticated');

create policy "insert messages" on public.message
for insert with check (auth.role() = 'authenticated');
